#! /usr/bin/python
# -*- coding: utf-8 -*-

__author__ = 'rh'
__date__ = "$18.07.2015 15:55:22$"

import os
import string
import ConfigParser  # read configfile

import p_glbls  # share global values
import p_utils
from   p_log import p_log_this
import p_cfg.patterns as patterns

# may be used in: def p_read_ini():
# pyprogen_ini = """
# [properties]
# prog_name = y_main
# """

def p_read_ini(dir_cfg='.', cfg_fn='pyprogen.ini'):
    """ reads defaults for generated program: name ..."""
    # http://www.karoltomala.com/blog/?p=622
    path = os.path.abspath(__file__)
    dir_path = os.path.dirname(path)
    print 'p_read_ini: dir_path = ', p_utils.p_act_dir_path()
    print 'p_read_ini: dir_path = ', dir_path
    print p_glbls.__file__
    p_log_this()
    cfg_path = os.path.join(dir_cfg, cfg_fn)
    cfg_path = os.path.normpath(cfg_path)
    parser = ConfigParser.SafeConfigParser(allow_no_value=True)
    # parser.readfp(io.BytesIO(pyprogen_ini))
    p_log_this('cfg_path: ' + cfg_path)
    cfg_file = parser.read(cfg_path)
    p_log_this('cfg file: ' + str(cfg_file))

    # p_glbls.prog_name
    try:
        p_glbls.prog_name = parser.get("properties", "prog_name")
        p_log_this('prog_name = ' + p_glbls.prog_name)
        if (len(p_glbls.prog_name) < 4):
            p_glbls.prog_name = p_glbls.prog_name + '.py'
            p_log_this('          =>' + p_glbls.prog_name)
        if ((string.lower(p_glbls.prog_name[-3:])) <> '.py'):
            p_glbls.prog_name = p_glbls.prog_name + '.py'
            p_log_this('          =>' + p_glbls.prog_name)
    except ConfigParser.NoOptionError:
        p_glbls.prog_name = 'z_main.py'
        p_log_this('no >prog_name< in: ' + cfg_path + ' !')
        p_log_this('prog_name set to: ' + p_glbls.prog_name)

    # p_glbls.prog_path
    p_glbls.prog_path = os.path.normpath(p_glbls.prog_name[:-3])
    print 'p_read_ini: p_glbls.prog_path = ', p_glbls.prog_path
    p_log_this("prog_path = " + p_glbls.prog_path)

    # p_glbls.prefix
    try:
        p_glbls.prefix = parser.get("properties", "prefix")
        p_log_this('prefix = ' + p_glbls.prefix)
        if (len(p_glbls.prefix) < 2):
            p_log_this('prefix = ' + p_glbls.prefix)
            p_glbls.prefix = p_glbls.prog_name[0] + '_'  # prefix for generated program
            p_log_this('prefix set to: ' + p_glbls.prefix)
    except ConfigParser.NoOptionError:
        p_glbls.prefix = p_glbls.prog_name[0] + '_'  # prefix for generated program
        p_log_this('prefix set to: ' + p_glbls.prefix)


def create_various_path_names():
    p_glbls.glbls_fn   = p_glbls.prefix + 'glbls.py'    # globals of >y_main.py< !
    p_glbls.glbls_path = os.path.join('.', p_glbls.dir_lib, p_glbls.glbls_fn)

    p_glbls.my_code_fn   = p_glbls.prefix + 'my_code.py'
    p_glbls.my_code_path = os.path.join('.', p_glbls.dir_lib, p_glbls.my_code_fn)


def p_subst(input_dict, outfile_fn, outfile_path):
    """ substitutes text in code parts
    (from dict from patterns.y_xxxx); writes to outfile """
    p_log_this()
    patts = dict()
    for key, patt in input_dict.iteritems():
        txt = patt.replace("xx_CAParser", p_glbls.CAParser_fn[:-3])
        txt =  txt.replace("xx_main",     p_glbls.prog_name[:-3])
        txt =  txt.replace("xx_parser",   p_glbls.CAParser_func)
        txt =  txt.replace("xx_glbls",    p_glbls.glbls_fn[:-3])
        txt =  txt.replace("xx_my_code",  p_glbls.my_code_fn[:-3])
        patts[key] = txt

    now_str = p_utils.p_make_act_date_str()
    p_log_this('writing: ' + outfile_path)
    with open(outfile_path, 'w') as outfile:
        outfile.write('# ' + now_str + ' generated by: >pyprogen.py<')
        #for key, patt in patts.iteritems():
        for key, patt in sorted(patts.iteritems()):
            outfile.write(patt)
        outfile.write('# ' + now_str)

def p_globals():
    """ creates ./y_main/lib/y_glbls.py """
    p_log_this(' begin')
    # fn and path of  >y_glbls.py<
    outfile_fn   = p_glbls.glbls_fn
    outfile_path = p_glbls.glbls_path
    # write code of  >y_glbls.py<

    txt = '\n# ----- optional args:\n'
    for arg in p_glbls.opt_arg_vars:
        txt = txt + arg + ' = None\n'
    txt = txt + '\n# ----- positional args:\n'
    for arg in p_glbls.pos_arg_vars:
        txt = txt + arg + ' = None\n'

    txt = txt + '\ndef print_cfg_args():\n'
    txt = txt + '    # optional args:\n'
    for arg in p_glbls.opt_arg_vars:
        txt = txt + '    print \'' + str(arg) + ' = \' + str(' + arg + ')\n'
    txt = txt + '\n'
    txt = txt + '    # positional args:\n'
    for arg in p_glbls.pos_arg_vars:
        txt = txt + '    print \'' + str(arg) + ' = \' + str(' + arg + ')\n'
    txt = txt + '\n\n'

    patterns.y_glbls[04] = txt

    p_subst(patterns.y_glbls, outfile_fn, outfile_path)
    p_log_this(' end' )


def p_my_code():
    """ creates y_main.py """
    p_log_this(' begin')
    # fn and path of  >y_main.py<
    outfile_fn = p_glbls.prog_name
    outfile_path = os.path.join(p_glbls.dir_main, outfile_fn)
    # write code of  >y_main.py<
    p_subst(patterns.y_main, outfile_fn, outfile_path)
    p_log_this(' end' )


def p_main():
    """ creates y_main.py """
    p_log_this(' begin')
    # fn and path of  >y_main.py<
    outfile_fn = p_glbls.prog_name
    outfile_path = os.path.join(p_glbls.dir_main, outfile_fn)
    # write code of  >y_main.py<
    p_subst(patterns.y_main, outfile_fn, outfile_path)
    p_log_this(' end' )


if __name__ == "__main__":
    print p_glbls.my_name()
    p_utils.p_exit()
